version: '3.3'
services:
  web:
    build:
      context: ./
    ports:
      - 8080:8080
    volumes:
      - "./:/go/src/app"
    depends_on:
      - redis
    environment: 
      GO_ENV: ${GO_ENV-development}
    command: air -d